name: run hardhat tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Change into contract directory
        run: cd contract

      - name: Install dependencies
        run: npm ci

      - name: Run Hardhat tests
        run: npx hardhat test